### PR TITLE
[WIP] Add collision checker

### PR DESCRIPTION
**Pull request by Qix-**
**NOTE:** This is based on #12. Please check/review/approve/deny/merge that one first.

Adds an official Meow collision checker.

Uses SHA-512 as secure hash with the assumption that it will never find a collision. The SHA-512 is then used to input de-dupe contents we've previously seen prior to passing it to the Meow collision checker.

It uses an mmap strategy to reduce I/O latency. **The windows code is untested** so can someone please try to build/test this and let me know? I went entirely based off of documentation from MSDN and knowledge of my early winapi programming days.

Here's the usage:

```console
$ meow_collidecheck [/path/to/dir]
```

(defaults to CWD if no path is passed)

For example:

```console
$ cd /tmp && mkdir test-meow && cd test-meow
$ npm i material-design-icons
$ meow_collidecheck /tmp/test-meow
num. files hashed:  89815
num considered:     32943
num skipped:        56872
total bytes hashed: 45864731 (43.74 MiB)
collisions:         0
```

If you disable SHA-512 collision (duplicate file) file skipping (by commenting out the `goto` and recompiling), you can see what it looks like if the meow collision checking finds a collision (since it doesn't validate file contents itself) - though of course those would be false positives.

### CODE REVIEW

**Comment by Qix-** [comment]
@cmuratori Your project is going to be much harder for others to contribute to if you don't have some base set of tooling for other users to use.

By closing all of the related PRs without any amount of discussion just indicates you're not interested in outside contributes, which is highly disappointing to see on Github.

What I was PRing in are improvements to help not only make things easier for others to contribute, but to make different platforms much less random - especially since Meow deals with a lot of platform-dependent code.

**Comment by mmozeiko** [comment]
You need to understand that contributions must be in similar style as original project intends. No serious open-source projects accept contributions where suddenly build system is completely changed - you want to use cmake, but what if somebody will want to use bazel? what about gyp? premake? autotools? etc... Or suddenly all the sources are reformatted /  whitespaces removed (what if somebody wants to use TAB instead of spaces). Or some custom IDE/editor config files are added.

**Comment by Qix-** [comment]
> bazel

That's fine.

> gyp

That's also fine.

> premake

That's still fine.

> autotools

Again, fine.

If the maintainer came back and said "I don't like CMake, let's use <insert> instead", as long as it's something that's usable cross-platform and keeps the guesswork out of building and running tests, that's really all that matters.

CMake was chosen because it's the most commonly used outside of autotools, which is becoming phased out as it's quite hard to include it in parent projects.

**Comment by cmuratori** [comment]
The next update has its own official collision checker, so this would be better maintained as a separate project.

\- Casey

**Pull request closed without merging**
