### PR TITLE
Add info about Rust port in README

### PR DESCRIPTION
**Pull request by yerke**
Add info about Rust port in README
cc @bodil

### CODE REVIEW

**Comment by cmuratori** [comment]
I am concerned that the license appears to be different.  Is there a reason it is not the same license as the original?

\- Casey

**Comment by yerke** [comment]
Only @bodil would be able to answer that. To be fair, most of Rust open source software is licensed Apache/MIT, so even in that case, it likely wouldn’t have been zlib.

Will the difference in license prevent it from being added to unofficial ports?

**Comment by cmuratori** [comment]
Well, it seems like the license should probably be the same, so people don't have to be confused about it... the other port listed here uses the same license.

\- Casey

**Comment by yerke** [comment]
It's unlikely that the license will be changed to zlib. Should I close this PR?

**Comment by NoHatCoder** [comment]
Is it really such a big issue? You don't have to agree that it is the best license choice to make a simple link.

**Comment by cmuratori** [comment]
I went ahead and fixed this by adding a note to the readme that explicitly mentions the possibility of unofficial ports having more restrictive licenses, so hopefully no one will be confused.

\- Casey

**Pull request merged**
