### PR TITLE
Move to CMake-based build

### PR DESCRIPTION
**Pull request by Qix-**
**NOTE:** based on #11. Review/merge that one first.

`build.bat` is great for windows, terrible for everyone else that wants to use it. CMake is (arguably) considered the industry standard at this point, and it makes integration with just about any project or workflow a breeze.

This is going to be easier to maintain than a separate build.bat/build.sh and be more accurate in terms of how to build things, too.

### CODE REVIEW

**Comment by cmuratori** [comment]
I don't use make systems, they overcomplicate things.

\- Casey

**Comment by Qix-** [comment]
I mean... Thats not objectively true. Can you justify your statement?

**Comment by mmozeiko** [comment]
Of course it is not objectively true. It is subjectively true. He says "I don't use", not that you should not use it.

With buid.bat you run it - you get output exe. It cannot be easier that that.

With cmake? You need run cmake (after figuring out correct arguments for cmake to specify your desired buildsystem), then you need to run build system (after figuring out how to install it), and only then you get exe (in some weird folder). Also a ton of useless files are generated during this process.

And anyways building is not actually needed if you want to use meow_hash - this is header-only library. build.bat is only for internal testing/benchmarking.

**Comment by Qix-** [comment]
> With buid.bat you run it - you get output exe. It cannot be easier that that.

It's not about easy. It's about making it compatible with people that are trying to help you develop your project.

However, right now it appears the maintainer isn't interest in public contributions.

> With cmake? You need run cmake

```console
$ mkdir build && cd build
$ cmake ..
```

> after figuring out correct arguments for cmake to specify your desired buildsystem

This is what README's are for.

> then you need to run build system

```console
$ make
```

or

```console
$ cmake --build=.
```

> after figuring out how to install it

```console
# mac
$ brew install cmake

# ubuntu
$ sudo apt install cmake

# fedora
$ yum install cmake

# arch
$ pacman -S cmake
```

On windows there an installer and a GUI for those that don't want to use the command line: https://cmake.org/runningcmake/

> and only then you get exe (in some weird folder)

It's literally in the directory you run cmake in. You can run it in the same directory directly after building.

```console
$ meow_collidecheck.exe
```

> Also a ton of useless files are generated during this process.

They're not useless otherwise they wouldn't be generated. Putting them in `build/` (which is the best practice) is called an "out of source" build which means you're not going to accidentally commit project files, build scripts, or artifacts.

**This is proper native development when writing OSS software.***

> And anyways building is not actually needed if you want to use meow_hash - this is header-only library.

No, you're right. If you want to easily include meow tests into a larger project, though, now you are at the mercy of an arbitrarily written `build.bat` or `build.sh` and random shell scripts are not easily integrated with larger build systems.

Again, this really comes down to the maintainer not being interested in PRs.

> build.bat is only for internal testing/benchmarking.

And now you have to support `build.bat` and `build.sh`, and others have to support it if they want to integrate tests into their system.

**Comment by mmozeiko** [comment]
I'm sure somebody who will be required to read through and understand the instructions similar to what you posted above will be capable of running `gcc -whateverargs file.cpp` on command-line. And as said above - it is not really required for meow_hash users.

**Comment by Qix-** [comment]
So windows users get a bat script but linux/mac users are forced to run individual commands?

That's terrible. That's unmaintainable. Further, I don't use `gcc`. What now? I have to research vectorization flags each time I want to use meow?

None of this makes any sense for hosting your code on Github.

**Comment by mmozeiko** [comment]
You hardcoded non-windows flags in cmake anyway. Its the same thing as you are asking me now. What if I don't want those or my compiler doesn't support them? Do I have to research how to hack/override them with my flags into your cmake script?

**Comment by Qix-** [comment]
> You hardcoded non-windows flags in cmake anyway.

Yes, for a specific platform. Not for windows users.

> Its the same thing as you are asking me now.

How do you figure? It's entirely different, did you read my "wall of text" or did you assume there was nothing interesting in it?

> What if I don't want those or my compiler doesn't support them? 

Then you add more checks to the cmake configuration to determine if they do.

> Do I have to research how to hack/override them with my flags into your cmake script?

No, unless you use a niche compiler that isn't gcc, clang, or msvc. CMake has the ability to check for a compiler ID and make decisions accordingly.

**Comment by mmozeiko** [comment]
My point is you hardcoded decision results in cmake, which will work only for gcc/clang based compilers.

Not sure what you mean about vectorization flags above to use meow. You need to use them anyway in your caller code. Because meow public API returns SIMD types. So it completely is irrelevant how bench / example is compiled. Your project that uses meow (not meow build.bat/sh) will need to have them - so you will have it already figured out.

How can you don't see that your answers are add more checks to cmake, or install this or that to run the build. How that is easier than build.bat/sh? All you repeat is "proper development" or something like "not a github way". Why your "proper" way is more proper than what other people are doing? Rhetorical question.

There is really no need for build system for this kind of project. Because there is nothing to build for users of it. If you are contributing to internals of meow_hash then you know how to build single .cpp file executables.

**Comment by Qix-** [comment]
> So it completely is irrelevant how bench / example is compiled.

Clang/GCC do not emit certain classes of vectorization instructions by default, nor do they include the intrinsics by default.

> How that is easier than build.bat/sh?

It's more proper.

> Why your "proper" way is more proper than what other people are doing?

Because it enables other users to _use_ meow and to check its correctness via tests.

> Rhetorical question.

No, it's not. Please stop dismissing my arguments because you disagree with them.

> There is really no need for build system for this kind of project. Because there is nothing to build for users of it.

Utilities and tests. So yes, there are.

> If you are contributing to internals of meow_hash then you know how to build single .cpp file executables.

That's a non-sequitur statement. Of course people know how to build single cpp files, but that has no bearing on contributing to meow. With that argument, there's no need for `built.bat` in the first place.

**Comment by mmozeiko** [comment]
What are you talking about? There are no utilities and no tests.

Yes, there is no need for build.bat. I completely agree to you on this one. But there is nothing wrong for Casey having it for his convenience, its his repo. This is the point you are missing, and instead just focusing on something you call "proper" github/opensource way.

**Comment by Qix-** [comment]
> There are no utilities and no tests.

- `meow_example.cpp`
- `meow_bench.cpp`
- `meow_smasher.cpp`
- `meow_collidecheck.cpp` (assuming #15 is merged)

And there should be tests.

**Comment by mmozeiko** [comment]
Please show me where GitHub requires to have buidsystem like you want it and not how author wants it.

**Pull request closed without merging**
