### PR TITLE
Compilation fixes with latest Clang trunk (8.0 pre-release)

### PR DESCRIPTION
**Pull request by aganea**

### CODE REVIEW

**Comment by cmuratori** [comment]
Looking at these changes, they do not seem like _required_ changes to me.  Fallthrough marking in particular, for example, is something I thought was only optional warning in C++17 and, to the best of my knowledge, is not at all something you are required to do... are you sure these are required to compile the code with Clang using default settings?

\- Casey

**Comment by cmuratori** [comment]
On Haswell AES instructions are 7 cycles instead of 4, so there is a significant speedup on Skylake-era hardware for Meow Hash.

Which algorithm are you referring to that is "memory bound"?  xxHash / xxHash3 cannot run at memory bandwidth on high-bandwidth systems (modern i7, i9, etc.).  See for example https://twitter.com/mmozeiko/status/1106714583761215488

\- Casey

**Comment by aganea** [comment]
I meant the function in LLD ([here](https://github.com/llvm/llvm-project/blob/master/llvm/lib/DebugInfo/CodeView/TypeHashing.cpp#L33)) that I modified to use Meow instead of SHA1. Unfortunately the data needs to be "prepared" before hashing it (the `discoverTypeIndices` call), so cache misses will occur outside/before the hasher. However that is mittigated (will be mittigated once commited) by multithreading at a higher level.

**Comment by cmuratori** [comment]
So, the "const" change is probably not something I will merge, although I will look into it further.  v0.5 of Meow Hash, which is coming shortly, does not use switches or a fallthrough, so that issue should resolve itself.

\- Casey

**Pull request closed without merging**
